title: "Ipek Selcen - Editorial Portfolio"
description: "Writing, mini-reviews, and scientific editing samples."
url: "https://ipekselcen.github.io"  
baseurl: "/editorial-portfolio"    

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "default"

defaults:
  - scope: { path: "" }
    values:
      layout: single

